#pragma once

typedef enum {
    ATLAS_PAGE_EYES = 0,
    ATLAS_PAGE_CLOCK,
    ATLAS_PAGE_STATUS,
    ATLAS_PAGE_VOICE,
    ATLAS_PAGE_SETTINGS,
    ATLAS_PAGE_ALARM,
    ATLAS_PAGE_PHOTO,
    ATLAS_PAGE_MUSIC,
    ATLAS_PAGE_STORY,
    ATLAS_PAGE_CHAT,
    ATLAS_PAGE_CALENDAR,
    ATLAS_PAGE_POMODORO,
} atlas_page_t;
